on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: jamesvirtudazo/stm32builder:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - run: make
      - run: make cppcheck
