on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: jamesvirtudazo/stm32-arm-none-eabi-15.2:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - run: TOOLS_PATH=/home/ubuntu/dev/arm-gnu-toolchain-15.2/bin make
      - run: make cppcheck
